In [1]:
"""
First let't enjoy numpy by importing it
"""
import numpy as np

In [2]:
"""Create array"""
"""Method1"""
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
"""
Method2
"""
np.zeros(10)
np.ones(3)
np.arange(1,15,2)
samples = np.random.normal(2,3,size=(4,4))
samples1 = np.random.randn(4,4)
draws = np.random.randint(0,10,size=(3,4))

In [5]:
"""
Method3
"""
x = np.array([1,2,4,5])
y = np.array([3,4,5])
#save方法可以存取一个ndarray
np.save("x_arr",x)
#如果要存取多个数组，要是用savez方法
np.savez("some_array.npz",xarr = x,yarr=y)
np.load('x_arr.npy')

array([1, 2, 4, 5])

In [6]:
arch = np.load("some_array.npz")
arch['yarr']

array([3, 4, 5])

In [10]:
arr = np.loadtxt('data/array_ex.txt',delimiter=',',dtype=np.int32)
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 7, 8, 9]], dtype=int32)

In [14]:
"""ndarray's attribute"""
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
#shape
arr2.shape

(2, 4)

In [15]:
#the element number of the ndarray
arr2.size

8

In [16]:
#ndarray.dtype:type of array element
arr2.dtype

dtype('int64')

In [17]:
#dimension
arr2.ndim

2

In [18]:
"""Some Computing Rules"""
arr = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]], dtype=float32)

In [19]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333334],
       [ 0.25      ,  0.2       ,  0.16666667]], dtype=float32)

In [20]:
"""Index and Slicing"""
"""
1、basic index and slice
Attention: the slicing is a shallow copy instead of deep copy
"""
arr = np.arange(10)
arr[5:8]=12
t = arr[5:8]
t[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [21]:
# if you want deep copy, use copy()
t1 = arr[5:8].copy()
t1[2] = -222
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [22]:
"""2、boolean index"""
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)

names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [23]:
data[names=='Bob']

array([[-0.64182386,  0.70880855, -0.2727907 , -0.86444065],
       [-1.35216864, -1.1006845 , -1.38757149, -0.08580659]])

In [24]:
# we can use logistic operation when using boolean index
data[(names=='Bob')| (names=='Will')]

array([[-0.64182386,  0.70880855, -0.2727907 , -0.86444065],
       [-0.60107905, -1.2835444 , -0.13403607,  0.3112887 ],
       [-1.35216864, -1.1006845 , -1.38757149, -0.08580659],
       [ 1.3437432 , -0.16359263,  0.27433455, -0.64077354]])

In [29]:
"""Transpose"""
arr = np.arange(15).reshape((5,3))
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [30]:
arr = np.arange(16).reshape((2,2,4))
arr
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [31]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [32]:
"""Some Basic Functions"""
"""1、General Function"""
#abs，sqrt，square，exp，log，maximum、minimum
arr = np.arange(10)
np.sqrt(arr)

x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y)

array([-0.48512501, -0.0569327 , -0.07323486, -0.73383152, -0.22405498,
        1.84138733, -0.41471046,  0.08337788])

In [33]:
"""2、where"""
#where
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
np.where(cond,xarr,yarr)

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [34]:
np.where(xarr>1.2,2,-2)

array([-2, -2,  2,  2,  2])

In [35]:
"""3、Statistical Methods"""

arr = np.random.randn(5,4)
arr.mean()
np.mean(arr)

0.020556179922288392

In [36]:

arr.mean(axis=1)

array([-0.62748671,  0.08606998,  0.48440001, -0.23932461,  0.39912223])

In [37]:
arr.sum(0)

array([ 2.82327303, -3.27565928, -2.40032697,  3.26383682])

In [38]:
"""4、sort"""
arr = np.random.randn(8)
arr

array([-0.19820571, -0.5433029 , -1.03868621,  0.05674864, -0.46440116,
       -0.51621002, -0.87766477,  0.88084224])

In [39]:
arr.sort()
arr

array([-1.03868621, -0.87766477, -0.5433029 , -0.51621002, -0.46440116,
       -0.19820571,  0.05674864,  0.88084224])

In [40]:
"""5、Set Function"""
arr = np.array([1,3,2,5,2,4,2,2,1,4,5,2])
np.unique(arr)

array([1, 2, 3, 4, 5])

In [41]:
"""
intersect1d(x,y)
union1d(x,y) 
setdiff1d(x,y)
"""
x = np.array([1,2,4,5])
y = np.array([3,4,5])
np.intersect1d(x,y)

array([4, 5])

In [42]:
np.union1d(x,y)

array([1, 2, 3, 4, 5])

In [43]:
np.setdiff1d(x,y)

array([1, 2])

In [44]:
"""6、Linear Algebra"""
# dot
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [45]:
# inverse
from numpy.linalg import inv,det,eig,qr,svd
t = np.array([[1,2,3],[2,3,4],[4,5,6]])
inv(t)

array([[ -1.20095990e+16,   1.80143985e+16,  -6.00479950e+15],
       [  2.40191980e+16,  -3.60287970e+16,   1.20095990e+16],
       [ -1.20095990e+16,   1.80143985e+16,  -6.00479950e+15]])

In [46]:
# det
det(t)

1.6653345369377289e-16

In [47]:
#QR Split
qr(t)

(array([[-0.21821789, -0.81649658, -0.53452248],
        [-0.43643578, -0.40824829,  0.80178373],
        [-0.87287156,  0.40824829, -0.26726124]]),
 array([[ -4.58257569e+00,  -6.11010093e+00,  -7.63762616e+00],
        [  0.00000000e+00,  -8.16496581e-01,  -1.63299316e+00],
        [  0.00000000e+00,   0.00000000e+00,   7.03584777e-16]]))

In [48]:
#singular value decomposition
svd(t)

(array([[-0.33735892, -0.77490301, -0.53452248],
        [-0.49235751, -0.33871366,  0.80178373],
        [-0.80235469,  0.53366505, -0.26726124]]),
 array([  1.09222648e+01,   8.39125544e-01,   3.10689920e-16]),
 array([[-0.41488581, -0.56431188, -0.71373795],
        [ 0.81314396,  0.12200588, -0.56913221],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [49]:
#eigen vector and eigen value
eig(t)

(array([  1.08309519e+01,  -8.30951895e-01,  -1.24701000e-16]),
 array([[ 0.34416959,  0.72770285,  0.40824829],
        [ 0.49532111,  0.27580256, -0.81649658],
        [ 0.79762415, -0.62799801,  0.40824829]]))